### ISSUE TITLE
EDTA fails on some fasta

### ISSUE THREAD

**Issue by aderzelle** [oushujun/EDTA#25]
Hello (it's me again sorry),

following issue #14 
I have a machine where I thought EDTA was running fine but it seems to work or not depending of the genome fasta provided. Here is what is happening with a fasta that seems to cause an error
I have removed any scaffolds below 5500 bp. The RepeatMasker and RepeatModeler used are not the ones from conda

```
Mon Oct  7 20:13:39 CEST 2019	Dependency checking:
				All passed!
Mon Oct  7 20:14:01 CEST 2019	Obtain raw TE libraries using various structure-based programs: 
Mon Oct  7 20:14:01 CEST 2019	EDTA_raw: Check files and dependencies, prepare working directories.

Mon Oct  7 20:14:01 CEST 2019	Start to find LTR candidates.

Mon Oct  7 20:14:01 CEST 2019	Identify LTR retrotransposon candidates from scratch.

Mon Oct  7 20:21:12 CEST 2019	Finish finding LTR candidates.

Mon Oct  7 20:21:12 CEST 2019	Start to find TIR candidates.

Mon Oct  7 20:21:12 CEST 2019	Identify TIR candidates from scratch.

Species: others
rm: cannot remove './TIR-Learner/*': No such file or directory
/home/lege/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lege/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lege/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lege/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/lege/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/lege/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/lege/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/lege/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/lege/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/lege/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/lege/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/lege/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/mnt/sdc1/Alessandro/TR_2013/EDTA/bin/TIR-Learner1.23/Module3_New/getDataset2.py", line 109, in Predict
    predicted_labels = model.predict(np.stack(prefeature))
  File "<__array_function__ internals>", line 6, in stack
  File "/home/lege/.local/lib/python3.6/site-packages/numpy/core/shape_base.py", line 421, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/sdc1/Alessandro/TR_2013/EDTA/bin/TIR-Learner1.23/Module3_New/getDataset2.py", line 130, in <module>
    d = pool.map(Predict,files)
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: need at least one array to stack
cat: '*-+-DTA.fa': No such file or directory
cat: '*-+-DTC.fa': No such file or directory
cat: '*-+-DTH.fa': No such file or directory
cat: '*-+-DTM.fa': No such file or directory
cat: '*-+-DTT.fa': No such file or directory
cat: '*-+-NonTIR.fa': No such file or directory
cat: '*-+-*-+-*.gff3': No such file or directory
rm: cannot remove '*-+-*-+-*.gff3': No such file or directory
Traceback (most recent call last):
  File "/mnt/sdc1/Alessandro/TR_2013/EDTA/bin/TIR-Learner1.23/Module3_New/CombineAll.py", line 90, in <module>
    keep=removeIRFhomo("%s.gff3"%(genome_Name+spliter+dataset),remove,"%sClean.gff3"%(genome_Name+spliter+dataset+spliter))
  File "/mnt/sdc1/Alessandro/TR_2013/EDTA/bin/TIR-Learner1.23/Module3_New/CombineAll.py", line 76, in removeIRFhomo
    f=pd.read_csv(file,header=None,sep="\t")
  File "/home/lege/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/lege/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/lege/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/lege/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/lege/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/mnt/sdc1/Alessandro/TR_2013/EDTA/bin/TIR-Learner1.23/Module3/GetAllSeq.py", line 32, in GetListFromFile
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/sdc1/Alessandro/TR_2013/EDTA/bin/TIR-Learner1.23/Module3/GetAllSeq.py", line 63, in <module>
    pool.map(GetListFromFile,fileList) #shujun
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
mv: cannot stat 'TIR-Learner/*FinalAnn.gff3': No such file or directory
mv: cannot stat 'TIR-Learner/*FinalAnn.fa': No such file or directory
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /mnt/sdc1/Alessandro/TR_2013/EDTA/util/rename_tirlearner.pl line 18.
Warning: LOC list long_scaffolds.fa.TIR.ext30.list is empty.
Warning: The TIR result file has 0 bp!

Mon Oct  7 20:57:12 CEST 2019	Start to find MITE candidates.

Mon Oct  7 20:57:12 CEST 2019	Identify MITE candidates from scratch.

Mon Oct  7 20:57:12 CEST 2019	Warning: Because MITE-Hunter is too slow and only contribute limited new TIR candidates, it is taken down temporary until a better solution is found.

As a temporary fix, the TIR-Learner is used to mock the MITE-Hunter result. Please run -type tir first.

Error: MITE results not found!

ERROR: Raw TIR results not found in long_scaffolds.fa.EDTA.raw/long_scaffolds.fa.TIR.raw.fa at ./EDTA/EDTA.pl line 177.
```
the fasta file can be sent to you if you would like to investigate. 
Thanks a  lot

**Comment by aderzelle** [comment]
Hello,
I kindly bump up this thread, I would like to know if I might be of any help to resolve further this issue, as so far EDTA gives  the kind of output I otherwise have troubles to obtain from other pipelines (hence I really would like to be able to run it on the different assemblies I have).
Thank a lot

**Comment by oushujun** [comment]
Hi @aderzelle,

Sorry for the delay response. We are working on this issue as well as the #14 issue. There will be an update to the EDTA program in two weeks.

Best,
Shujun

**Comment by oushujun** [comment]
Hi @aderzelle ,

This issue should be solved in the current update. Please help to test it out.

Best,
Shujun

**Comment by aderzelle** [comment]
Hello,
I am doing this this week, thanks a lot! I let you know.

**Comment by aderzelle** [comment]
Hello, so I ran it, the run completed and produced a folder

> long_scaffolds.fa.EDTA.raw

However, no consensus file and it returner the following error (note that this did not cause EDTA to stop running) 

```
multiprocessing.pool.RemoteTraceback:                                                                                                                                                               [39/109]
"""
Traceback (most recent call last):
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/mnt/sdc1/Alessandro/TR_2013/EDTA/bin/TIR-Learner2.4/Module3_New/getDataset.py", line 111, in Predict
    predicted_labels = model.predict(np.stack(prefeature))
  File "<__array_function__ internals>", line 6, in stack
  File "/home/lege/.local/lib/python3.6/site-packages/numpy/core/shape_base.py", line 421, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/sdc1/Alessandro/TR_2013/EDTA/bin/TIR-Learner2.4/Module3_New/getDataset.py", line 132, in <module>
    d = pool.map(Predict,files)
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: need at least one array to stack
cat: '*-+-DTA.fa': No such file or directory
cat: '*-+-DTC.fa': No such file or directory
cat: '*-+-DTH.fa': No such file or directory
cat: '*-+-DTM.fa': No such file or directory
cat: '*-+-DTT.fa': No such file or directory
cat: '*-+-NonTIR.fa': No such file or directory
cat: '*-+-*-+-*.gff3': No such file or directory
rm: cannot remove '*-+-*-+-*.gff3': No such file or directory
Traceback (most recent call last):
  File "/mnt/sdc1/Alessandro/TR_2013/EDTA/bin/TIR-Learner2.4/Module3_New/CombineAll.py", line 75, in <module>
    f_m3=removeDupinSingle("%s.gff3"%(genome_Name+spliter+"Module3"))
  File "/mnt/sdc1/Alessandro/TR_2013/EDTA/bin/TIR-Learner2.4/Module3_New/CombineAll.py", line 57, in removeDupinSingle
    f=pd.read_csv(file,header=None,sep="\t") #shujun
  File "/home/lege/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/lege/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/lege/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/home/lege/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/lege/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1917, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/mnt/sdc1/Alessandro/TR_2013/EDTA/bin/TIR-Learner2.4/Module3/GetAllSeq.py", line 32, in GetListFromFile
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/sdc1/Alessandro/TR_2013/EDTA/bin/TIR-Learner2.4/Module3/GetAllSeq.py", line 63, in <module>
    pool.map(GetListFromFile,fileList) #shujun
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/lege/anaconda3/envs/EDTA/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn.gff3'
mv: cannot stat 'TIR-Learner/*FinalAnn*.gff3': No such file or directory
mv: cannot stat 'TIR-Learner/*FinalAnn*.fa': No such file or directory
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: No such file or directory at /mnt/sdc1/Alessandro/TR_2013/EDTA/util/rename_tirlearner.pl line 18.
Warning: LOC list long_scaffolds.fa.TIR.ext30.list is empty.
Can't exec "long_scaffolds.fa.TIR.ext30.fa.pass.fa.dusted": No such file or directory at /mnt/sdc1/Alessandro/TR_2013/EDTA/util/cleanup_tandem.pl line 77.
Use of uninitialized value $tandem in substitution (s///) at /mnt/sdc1/Alessandro/TR_2013/EDTA/util/cleanup_tandem.pl line 78.
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: No such file or directory.
Warning: The TIR result file has 0 bp!

Tue Nov 12 18:13:08 CET 2019    Start to find Helitron candidates.

Tue Nov 12 18:13:08 CET 2019    Identify Helitron candidates from scratch.

Can't exec "long_scaffolds.fa.HelitronScanner.filtered.ext.fa.pass.fa.dusted": No such file or directory at /mnt/sdc1/Alessandro/TR_2013/EDTA/util/cleanup_tandem.pl line 77.
Use of uninitialized value $tandem in substitution (s///) at /mnt/sdc1/Alessandro/TR_2013/EDTA/util/cleanup_tandem.pl line 78.
Tue Nov 12 19:45:23 CET 2019    Warning: The Helitron result file has 0 bp!

Tue Nov 12 19:45:23 CET 2019    Execution of EDTA_raw.pl is finished!

ERROR: Raw TIR results not found in long_scaffolds.fa.EDTA.raw/long_scaffolds.fa.TIR.raw.fa at ./EDTA/EDTA.pl line 231.
```

**Comment by oushujun** [comment]
Hi @aderzelle,

Did you run from a broken previous run? If the error persists you may want to delete the entire *raw/TIR folder and rerun EDTA.

Best,
Shujun

**Comment by oushujun** [comment]
Hi @aderzelle,

This should be a bug in TIR-Learner and we are working to fix this. We should be able to push an update soon.

Shujun

**Comment by aderzelle** [comment]
Ok great,

I confirm it's not from a broken previous run. 
thank you

**Comment by oushujun** [comment]
Hi @aderzelle,

Has your issue been resolved by updating EDTA to v1.6.2?

Best,
Shujun

**Comment by aderzelle** [comment]
I am currently running it!

**Comment by aderzelle** [comment]
It's still running but it has shown an error 

```
Can't exec "A_vaga.FLYE.sixLongest.fa.LTR.intact.fa.ori.dusted": No such file or directory at /mnt/sdc1/Alessandro/TR_annotation_V3/EDTA/util/cleanup_tandem.pl line 77.                                   
Use of uninitialized value $tandem in substitution (s///) at /mnt/sdc1/Alessandro/TR_annotation_V3/EDTA/util/cleanup_tandem.pl line 78.
```
the run is still going anyway

**Comment by oushujun** [comment]
I have pushed a small fix for this issue. Please help to check if the issue persists. Thanks!

**Comment by aderzelle** [comment]
Hello, 
I have just checked it doesn't solve the error

```
sh: 0: Illegal option -N                                                                                                                                                                                    
Can't exec "-cleanN": No such file or directory at /mnt/sdc1/Alessandro/TR_annotation_V3/EDTA/util/cleanup_tandem.pl line 77.                                                                               
Use of uninitialized value $tandem in substitution (s///) at /mnt/sdc1/Alessandro/TR_annotation_V3/EDTA/util/cleanup_tandem.pl line 78
```
and further away
```

sh: 0: Illegal option -N
Can't exec "-cleanN": No such file or directory at /mnt/sdc1/Alessandro/TR_annotation_V3/EDTA/util/cleanup_tandem.pl line 77.
Use of uninitialized value $tandem in substitution (s///) at /mnt/sdc1/Alessandro/TR_annotation_V3/EDTA/util/cleanup_tandem.pl line 78.
Wed Nov 20 15:09:10 CET 2019    Finish finding Helitron candidates.
```
The run completes anyway and I don't know if the results are impacted. At first glance all the output files are present.

**Comment by oushujun** [comment]
Hi @aderzelle,

An easy fix: under the EDTA conda env, install `trf`:
`conda install -n EDTA -y trf`

You may also want to update EDTA but I just added a couple lines to check whether `trf` is installed. 

Thanks for testing,

Shujun

**Comment by aderzelle** [comment]
Hello,
that worked, no more error message. Just left is the following code warning (but it's not important now)
```
/home/lege/anaconda3/envs/EDTA/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of
 numpy, it will be understood as (type, (1,)) / '(1,)type'.  
```
I am gonna try EDTA on several other fasta files but it seems good. I will report if any issue arises.

**Comment by aderzelle** [comment]
Hello,
is it normal that the number of sequences in the TElib.fa is hugely reduced? 
Basically, before the last commit I had 4874 sequences, and with the last version of EDTA I end up with 459 sequences in the TElib.fa fasta. 

Did you remove elements, or change the way the consensus is reported?

**Comment by oushujun** [comment]
Hi @aderzelle,

The filtering algorithm was updated and the TIR-Learner pipeline also received huge updates. So it's likely you get a different number of sequences at the end. Did you use the library to generate whole-genome annotation? They probably stay relatively similar on numbers despite the annotation is improved in the current version.

Best,
Shujun

**Comment by aderzelle** [comment]
Yes I just did with RepeatMaskers and the results are hugely different actually, for the DTT class we go from 18% to 0,17 %!

**Comment by oushujun** [comment]
Is it just DTT or also with others? DTT was the category that got improved.
Previous version was too inclusive and had lots of false positives.

Shujun

**Comment by aderzelle** [comment]
Most of the changes are due to DTT.  However there is a general overall decrease in TEs found, albite in other categories than DTT the change is much smaller. 
Here are the 2 summaries 
Older EDTA release

```
DNA                    --           --           --   
    DTA                1279         332979       0.29% 
    DTC                1242         327991       0.28% 
    DTH                9610         3325568      2.86% 
    DTM                12196        4446671      3.82% 
    DTT                53385        21173911     18.19% 
    Helitron           1649         459227       0.39% 
LTR                    --           --           --   
    Gypsy              422          378711       0.33% 
    unknown            1306         908073       0.78% 
MITE                   --           --           --   
    DTA                721          80395        0.07% 
    DTC                38           10628        0.01% 
    DTH                311          54148        0.05% 
    DTM                728          101759       0.09% 
    DTT                2923         481260       0.41% 
                      ---------------------------------
    total interspersed 85810        32081321     27.56%
```

Last EDTA commit 

```
DNA                    --           --           --   
    DTA                2638         619029       0.53% 
    DTC                2013         649044       0.56% 
    DTH                112          22141        0.02% 
    DTM                6296         1883719      1.62% 
    DTT                994          201711       0.17% 
    Helitron           2490         625242       0.54% 
LTR                    --           --           --   
    Gypsy              493          388686       0.33% 
    unknown            2499         1284106      1.10% 
MITE                   --           --           --   
    DTA                1170         141860       0.12% 
    DTC                462          100749       0.09% 
    DTM                655          60925        0.05% 
    DTT                19           4365         0.00% 
                      ---------------------------------
    total interspersed 19841        5981577      5.14%
```

**Comment by oushujun** [comment]
Looks like EDTA ran correctly. Does 5.14% meet your expectation?

**Comment by aderzelle** [comment]
Ahah that's actually the core of the question ... But let's say we have previous pieces of evidence that the organism we are studying might have a few percent only of its genome made out of TEs. Being a putative asexual, it would make sense it has mechanisms to prevent TE proliferation.
There is still work to do but this figure given now by EDTA is certainly not outrageous.  I will inform you if anything relevant to EDTA comes up. 

Thanks  a lot for EDTA and the feedbacks, much appreciated.

**Comment by oushujun** [comment]
I am glad the results make sense. Let me know if you have new questions or
issues. Thanks for testing EDTA.

Best,
Shujun

**Comment by oushujun** [comment]
I close this thread as the bug seems to be resolved. Please reopen it if you find the same issue.
