### ISSUE TITLE
Installation: ClobberError: This transaction has incompatible packages due to a shared path.

### ISSUE THREAD

**Issue by DrHogart** [oushujun/EDTA#79]
Hello,
while running EDTA (from GitHub, all dependencies were installed using conda) I've faced with issue resulted with failed TIR analysis:

```{bash}
../EDTA/EDTA.pl --genome ../assembly/ref.fa -t 20                                                                                                                     

########################################################
##### Extensive de-novo TE Annotator (EDTA) v1.8.4  ####
##### Shujun Ou (shujun.ou.1@gmail.com)             ####
########################################################



Ср апр 29 00:20:04 MSK 2020     Dependency checking:
                                All passed!

Ср апр 29 00:20:28 MSK 2020     Obtain raw TE libraries using various structure-based programs: 
Ср апр 29 00:20:28 MSK 2020     EDTA_raw: Check dependencies, prepare working directories.

Ср апр 29 00:20:33 MSK 2020     Start to find LTR candidates.

Ср апр 29 00:20:33 MSK 2020     Existing result file ref.fa.mod.LTR.raw.fa found! Will keep this file without rerunning this module.
        Please specify --overwrite 1 if you want to rerun this module.

Ср апр 29 00:20:33 MSK 2020     Finish finding LTR candidates.

Ср апр 29 00:20:33 MSK 2020     Start to find TIR candidates.

Ср апр 29 00:20:33 MSK 2020     Identify TIR candidates from scratch.

Species: others
/state/partition1/raid10/work/TE_apr2020/EDTA/bin/TIR-Learner2.5/TIR-Learner2.5.sh: line 290: 27033 Недопустимая инструкция                     (core dumped) python3 $path/Module3_New/getDataset.py -g $genomeFile -name $genomeName -p $path -t $t -d $dir"/Module3_New"
cat: *-+-DTA.fa: Нет такого файла или каталога
cat: *-+-DTC.fa: Нет такого файла или каталога
cat: *-+-DTH.fa: Нет такого файла или каталога
cat: *-+-DTM.fa: Нет такого файла или каталога
cat: *-+-DTT.fa: Нет такого файла или каталога
cat: *-+-NonTIR.fa: Нет такого файла или каталога
cat: *-+-*-+-*.gff3: Нет такого файла или каталога
rm: невозможно удалить «*-+-*-+-*.gff3»: Нет такого файла или каталога
Traceback (most recent call last):
  File "/state/partition1/raid10/work/TE_apr2020/EDTA/bin/TIR-Learner2.5/Module3_New/CombineAll.py", line 75, in <module>
    f_m3=removeDupinSingle("%s.gff3"%(genome_Name+spliter+"Module3"))
  File "/state/partition1/raid10/work/TE_apr2020/EDTA/bin/TIR-Learner2.5/Module3_New/CombineAll.py", line 57, in removeDupinSingle
    f=pd.read_csv(file,header=None,sep="\t") #shujun
  File "/export/home/hogart/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/export/home/hogart/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/export/home/hogart/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/export/home/hogart/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/export/home/hogart/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 532, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file                                                                                                                                             [1615/1812]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/export/home/hogart/miniconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/export/home/hogart/miniconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/state/partition1/raid10/work/TE_apr2020/EDTA/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 32, in GetListFromFile
    f=open(file,"r+")
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/state/partition1/raid10/work/TE_apr2020/EDTA/bin/TIR-Learner2.5/Module3/GetAllSeq.py", line 63, in <module>
    pool.map(GetListFromFile,fileList) #shujun
  File "/export/home/hogart/miniconda3/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/export/home/hogart/miniconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'TIR-Learner_FinalAnn_filter.gff3'
mv: не удалось выполнить stat для «TIR-Learner/*FinalAnn*.gff3»: Нет такого файла или каталога
mv: не удалось выполнить stat для «TIR-Learner/*FinalAnn*.fa»: Нет такого файла или каталога
Can't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.fa: Нет такого файла или каталога at /state/partition1/raid10/work/TE_apr2020/EDTA/util/rename_tirlearner.pl line 18.
Warning: LOC list ref.fa.mod.TIR.ext30.list is empty.

Error: Error while loading sequenceCan't open ./TIR-Learner-Result/TIR-Learner_FinalAnn.gff3: Нет такого файла или каталога.
Warning: The TIR result file has 0 bp!

Ср апр 29 00:21:35 MSK 2020     Start to find Helitron candidates.

Ср апр 29 00:21:35 MSK 2020     Existing result file ref.fa.mod.Helitron.raw.fa found! Will keep this file without rerunning this module.
        Please specify -overwrite 1 if you want to rerun this module.

Ср апр 29 00:21:35 MSK 2020     Finish finding Helitron candidates.

Ср апр 29 00:21:35 MSK 2020     Execution of EDTA_raw.pl is finished!

ERROR: Raw TIR results not found in ref.fa.mod.EDTA.raw/ref.fa.mod.TIR.raw.fa
        If you believe the program is working properly, this may be caused by the lack of intact TIRs in your genome. Consider to use the --force 1 parameter to overwrite this check
```

Are there any ways to resolve this?

**Comment by oushujun** [comment]
Hello,

Please test with a fly or an Arabidopsis genome to make sure the program is running properly. For this case you can test with `EDTA_raw.pl --type tir`.

Best,
Shujun

**Comment by DrHogart** [comment]
Thanks for the feedback. I'he run the program with dm3 genome and get the same error.

`CentOS Linux release 7.6.1810 (Core)`
`3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by oushujun** [comment]
You may want to reinstall the EDTA environment. Did you install dependencies separately or all at once with the bioconda EDTA recipe?

**Comment by DrHogart** [comment]
Well..
the fresh conda installation in the novel env also failed:
`conda install -c bioconda -c conda-forge edta`

```{bash}
ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::perl-compress-raw-bzip2-2.087-pl526he1b5a44_0, bioconda/linux-64::perl-digest-hmac-1.03-pl526_3, bioconda/linux-64::perl-digest-md5-2.55-pl526_0, bioconda/linux-64::perl-extutils-m
akemaker-7.36-pl526_1, bioconda/linux-64::perl-html-tagset-3.20-pl526_3, bioconda/linux-64::perl-io-html-1.001-pl526_2, bioconda/linux-64::perl-io-zlib-1.10-pl526_2, conda-forge/linux-64::perl-text-soundex-3.05-
pl526_1000, bioconda/linux-64::perl-json-4.02-pl526_0
  path: 'lib/5.26.2/x86_64-linux-thread-multi/perllocal.pod'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/blast_formatter'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/blastdb_aliastool'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/blastdbcheck'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/blastdbcmd'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/blastn'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/blastp'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/convert2blastmask'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/datatool'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/deltablast'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/dustmasker'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/get_species_taxids.sh'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/get_species_taxids.sh.bak'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/legacy_blast.pl'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/makeblastdb'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/makembindex'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/makeprofiledb'
 
 
 ClobberError: This transaction has incompatible packages due to a shared path.                                                                                                                           [532/1688]
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/project_tree_builder'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/psiblast'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/rpsblast'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/rpstblastn'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/run_with_lock'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/segmasker'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/tblastn'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/tblastx'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/update_blastdb.pl'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/update_blastdb.pl.bak'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/windowmasker'


ClobberError: This transaction has incompatible packages due to a shared path.                                                                                                                           [477/1688]
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'bin/windowmasker_2.2.22_adapter.py'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libalign_format.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libbiblio.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libblast.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libblast_app_util-static.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libblast_app_util.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libblast_services.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libblastdb.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libblastdb_format.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libblastinput.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libblastxml.so'

ClobberError: This transaction has incompatible packages due to a shared path.                                                                                                                           [422/1688]
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libblastxml2.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libcomposition_adjustment.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libconnect.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libcreaders.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libgbseq.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libgene_info.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libgeneral.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libgenome_collection.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libid1.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libid2.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/liblmdb.so'
  
ClobberError: This transaction has incompatible packages due to a shared path.                                                                                                                           [367/1688]
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libmedlars.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libmedline.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libmla.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libmlacli.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xloader_blastdb.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xloader_blastdb_rmt.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xloader_genbank-static.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xloader_genbank.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xloader_genbank.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xreader-static.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xreader.a'
  
 ClobberError: This transaction has incompatible packages due to a shared path.                                                                                                                           [312/1688]
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xreader.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xreader_cache-static.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xreader_cache.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xreader_cache.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xreader_id1-static.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xreader_id1.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xreader_id1.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xreader_id2-static.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xreader_id2.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libncbi_xreader_id2.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libproteinkmer.so'
  
 ClobberError: This transaction has incompatible packages due to a shared path.                                                                                                                           [257/1688]
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libpub.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libpubmed.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libscoremat.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libseq.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libseqcode.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libseqdb.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libseqedit.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libseqmasks_io.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libseqset.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libseqsplit.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libsequtil.so'


ClobberError: This transaction has incompatible packages due to a shared path.                                                                                                                           [202/1688]
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libsubmit.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libtables.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libtaxon1.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libtaxon3.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libtest_mt.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libvalid.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libvariation.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libwritedb.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxalgoblastdbindex.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxalgodustmask.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxalgosegmask.so'
  
 ClobberError: This transaction has incompatible packages due to a shared path.                                                                                                                           [147/1688]
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxalgowinmask.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxalnmgr.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxblast.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxblastformat.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxcgi.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxcleanup.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxcompress.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxconnect.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxformat.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxhtml.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxlogging.so'
  
 ClobberError: This transaction has incompatible packages due to a shared path.                                                                                                                            [92/1688]
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxncbi.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxnetblast.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxnetblastcli.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxobjedit.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxobjmgr.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxobjread.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxobjsimple.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxobjutil.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxregexp.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxregexp_template_tester.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxser.so'
  
ClobberError: This transaction has incompatible packages due to a shared path.
  packages: bioconda/linux-64::blast-2.9.0-pl526h3066fca_4, bioconda/linux-64::rmblast-2.9.0-h2d02072_0
  path: 'lib/ncbi-blast+/libxutil.so'

done
Executing transaction: done
```

**Comment by oushujun** [comment]
This is new to me. Did you install in an existing environment or a
dedicated new environment?

**Comment by DrHogart** [comment]
It was novel dedicated conda env

сб, 2 мая 2020 г., 19:48 Shujun Ou <notifications@github.com>:

**Comment by oushujun** [comment]
Sorry for delay response. In this case you may try to install step by step, or using the platform-independent singularity version.

**Comment by DrHogart** [comment]
Clobber issue was fixed by 
```{bash}
conda clean -all
```

**Comment by oushujun** [comment]
Please let me know if you have other issues.

**Comment by GulRukhKhan2022** [comment]
I have one issue.
I have developed and algorithm by using Mask RCNN, Python code of trained model with 4 classes.
The algorithm is running on CPU but not running on GPU giving tensorflow and keras errors.
On CPU I have installed tensorflow==1.13.1, Keras==4.5.3.56 and working properly.
Anyone can help me to create CUDA environment to RUN the algorithm on GPU and obliged, please.
Even, I can pay for this task as well. please, contact me as soon as possible, I am in trouble.
thanks
Contact: gkhan@ithel.it
+39 34 98 71 2606
Gul Rukh

**Comment by Surbhigrewal** [comment]
> Clobber issue was fixed by
> 
> ```
> conda clean --all
> ```

This did not work for me. I am still unable to install on new conda env using mamba install on a linux machine.

When I use a MacOS I get:

Looking for: ['edta']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
bioconda/osx-arm64                                          Using cache
bioconda/noarch                                             Using cache
pkgs/main/osx-arm64                                           No change
pkgs/r/osx-arm64                                              No change
pkgs/main/noarch                                              No change
pkgs/r/noarch                                                 No change
Could not solve for environment specs
The following package could not be installed
└─ edta   is uninstallable because it requires
   └─ blast  , which does not exist (perhaps a missing channel).

Any suggestions?

**Comment by oushujun** [comment]
You may need to specify -c bioconda -c conda-forge. Also use the unlimited
file to install. The conda recipe is not ready

Shujun
